import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.css'

// Import the Inter font from next/font/google
const inter = Inter({ subsets: ['latin'] })

// Metadata for the website (used for SEO and browser title)
export const metadata: Metadata = {
  title: 'Create Next App', // Title shown in the browser tab
  description: 'Generated by create next app', // Description for search engines
}

// Root layout component (wraps all pages in the app)
export default function RootLayout({
  children,
}: {
  children: React.ReactNode // Children = all page content inside the layout
}) {
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
